# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ronda-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources: 
#     requests:
#       storage: 200Mi
#   storageClassName: local-storage