apiVersion: v1
kind: PersistentVolume
metadata:
  name: ronda-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/Users/mozennou/Desktop/Ronda-deploy/volume"
