apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
    backend: ronda
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
