name: Deploy to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:

    permissions:
      actions: read
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Create .env file
        run: |
            cat << EOF > .env
            POSTGRES_USER=${{ vars.POSTGRES_USER }}
            POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
            POSTGRES_DB=${{ vars.POSTGRES_DB }}
            POSTGRES_PASSWD=${{ secrets.POSTGRES_PASSWD }}
            REDIS_PASSWD=${{ secrets.REDIS_PASSWD }}
            EOF

      - name: Deployment
        run: |
          kubectl create secret generic app-secret --from-env-file=.env || true
          kubectl label secret app-secret backend=ronda
          kubectl apply -f ./k8s
        
